CREATE TABLE IF NOT EXISTS themes (
  uuid VARCHAR(64) NOT NULL PRIMARY KEY,
  icon TEXT NOT NULL,
  settings JSON NOT NULL,
  readme JSON NULL,
  page JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SET @themes_table := 'themes';
SET @db := DATABASE();

SET @has_uuid := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND COLUMN_NAME = 'uuid'
);
SET @sql := IF(@has_uuid = 0, 'ALTER TABLE themes ADD COLUMN uuid VARCHAR(64) NOT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @has_icon := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND COLUMN_NAME = 'icon'
);
SET @sql := IF(@has_icon = 0, 'ALTER TABLE themes ADD COLUMN icon TEXT NOT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @has_settings := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND COLUMN_NAME = 'settings'
);
SET @sql := IF(@has_settings = 0, 'ALTER TABLE themes ADD COLUMN settings JSON NOT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @has_readme := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND COLUMN_NAME = 'readme'
);
SET @sql := IF(@has_readme = 0, 'ALTER TABLE themes ADD COLUMN readme JSON NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @has_page := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND COLUMN_NAME = 'page'
);
SET @sql := IF(@has_page = 0, 'ALTER TABLE themes ADD COLUMN page JSON NOT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @has_created_at := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND COLUMN_NAME = 'created_at'
);
SET @sql := IF(@has_created_at = 0, 'ALTER TABLE themes ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @has_updated_at := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND COLUMN_NAME = 'updated_at'
);
SET @sql := IF(@has_updated_at = 0, 'ALTER TABLE themes ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @pk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = @themes_table AND CONSTRAINT_TYPE = 'PRIMARY KEY'
);
SET @sql := IF(@pk_exists = 0, 'ALTER TABLE themes ADD PRIMARY KEY (uuid)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;